function [Tiempos,Amplitudg,Nombre] = VibsLibresNoAmort()
workbookFile = 'ITEM1_20200624-111647_VibsLibresNoAmort.xlsx';
sheetName = 'lvtemporary_164710';
startRow = 6739;
endRow = 17000;
Nombre = 'Vibraciones libres no amortiguadas';
%IMPORTFILE Import data from a spreadsheet
%   [Tiempos,Amplitudg] = IMPORTFILE(FILE) reads data from the first
%   worksheet in the Microsoft Excel spreadsheet file named FILE and
%   returns the data as column vectors.
%
%   [Tiempos,Amplitudg] = IMPORTFILE(FILE,SHEET) reads from the specified
%   worksheet.
%
%   [Tiempos,Amplitudg] = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from
%   the specified worksheet for the specified row interval(s). Specify
%   STARTROW and ENDROW as a pair of scalars or vectors of matching size
%   for dis-contiguous row intervals. To read to the end of the file
%   specify an ENDROW of inf.
%
%	Non-numeric cells are replaced with: NaN
%
% Example:
%   [Tiempos,Amplitudg] = importfile('ITEM1_20200624-111647_VibsLibresNoAmort.xlsx','lvtemporary_164710',2,61441);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2021/06/19 17:49:23

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, sprintf('A%d:B%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:B%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
I = cellfun(@(x) ischar(x), raw);
raw(I) = {NaN};
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Tiempos = data(:,1);
Amplitudg = data(:,2);

%% Mover el 0
Tiempos = Tiempos - Tiempos(1);

