function [Tiempos, Amplitudg, Nombre] = VibsLibresAmort()
workbookFile = 'ITEM1_20200624-110547_VibsLibresAmort.xlsx';
sheetName = '20200624-110547_VibsLibresAmort';
Nombre = 'Vibraciones libres amortiguadas';
%IMPORTFILE Import data from a spreadsheet
%  [TIEMPOS, AMPLITUDG] = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as column vectors.
%
%  [TIEMPOS, AMPLITUDG] = IMPORTFILE(FILE, SHEET) reads from the
%  specified worksheet.
%
%  [TIEMPOS, AMPLITUDG] = IMPORTFILE(FILE, SHEET, DATALINES) reads from
%  the specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [Tiempos, Amplitudg] = importfile("C:\Users\asd\Documents\UdeC Personal\Cuarto año\Semestre 1\Análisis de sistemas dinámicos\mediciones\ITEM1_20200624-110547_VibsLibresAmort.xlsx", "20200624-110547_VibsLibresAmort", [2, 12289]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Jun-2021 21:03:29

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

dataLines = [3168, 12289];

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":B" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Tiempos", "Amplitudg"];
opts.VariableTypes = ["double", "double"];

% Import the data
tbl = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":B" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    tbl = [tbl; tb]; %#ok<AGROW>
end

%% Convert to output type
Tiempos = tbl.Tiempos;
Amplitudg = tbl.Amplitudg;
%% Mover el 0
Tiempos = Tiempos - Tiempos(1);

end